//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientWebServiceSoap.ServiceSoap {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.hd.saifdine.ma/", ConfigurationName="ServiceSoap.WebServiceSoapImpl")]
    public interface WebServiceSoapImpl {
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.hd.saifdine.ma/WebServiceSoapImpl/getComptesRequest", ReplyAction="http://ws.hd.saifdine.ma/WebServiceSoapImpl/getComptesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClientWebServiceSoap.ServiceSoap.getComptesResponse getComptes(ClientWebServiceSoap.ServiceSoap.getComptesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.hd.saifdine.ma/WebServiceSoapImpl/getComptesRequest", ReplyAction="http://ws.hd.saifdine.ma/WebServiceSoapImpl/getComptesResponse")]
        System.Threading.Tasks.Task<ClientWebServiceSoap.ServiceSoap.getComptesResponse> getComptesAsync(ClientWebServiceSoap.ServiceSoap.getComptesRequest request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.hd.saifdine.ma/WebServiceSoapImpl/getCompteRequest", ReplyAction="http://ws.hd.saifdine.ma/WebServiceSoapImpl/getCompteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClientWebServiceSoap.ServiceSoap.getCompteResponse getCompte(ClientWebServiceSoap.ServiceSoap.getCompteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.hd.saifdine.ma/WebServiceSoapImpl/getCompteRequest", ReplyAction="http://ws.hd.saifdine.ma/WebServiceSoapImpl/getCompteResponse")]
        System.Threading.Tasks.Task<ClientWebServiceSoap.ServiceSoap.getCompteResponse> getCompteAsync(ClientWebServiceSoap.ServiceSoap.getCompteRequest request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.hd.saifdine.ma/WebServiceSoapImpl/conversionRequest", ReplyAction="http://ws.hd.saifdine.ma/WebServiceSoapImpl/conversionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClientWebServiceSoap.ServiceSoap.conversionResponse conversion(ClientWebServiceSoap.ServiceSoap.conversionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.hd.saifdine.ma/WebServiceSoapImpl/conversionRequest", ReplyAction="http://ws.hd.saifdine.ma/WebServiceSoapImpl/conversionResponse")]
        System.Threading.Tasks.Task<ClientWebServiceSoap.ServiceSoap.conversionResponse> conversionAsync(ClientWebServiceSoap.ServiceSoap.conversionRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.hd.saifdine.ma/")]
    public partial class compte : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codeField;
        
        private double soldeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double solde {
            get {
                return this.soldeField;
            }
            set {
                this.soldeField = value;
                this.RaisePropertyChanged("solde");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getComptes", WrapperNamespace="http://ws.hd.saifdine.ma/", IsWrapped=true)]
    public partial class getComptesRequest {
        
        public getComptesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getComptesResponse", WrapperNamespace="http://ws.hd.saifdine.ma/", IsWrapped=true)]
    public partial class getComptesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.hd.saifdine.ma/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClientWebServiceSoap.ServiceSoap.compte[] @return;
        
        public getComptesResponse() {
        }
        
        public getComptesResponse(ClientWebServiceSoap.ServiceSoap.compte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCompte", WrapperNamespace="http://ws.hd.saifdine.ma/", IsWrapped=true)]
    public partial class getCompteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.hd.saifdine.ma/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public getCompteRequest() {
        }
        
        public getCompteRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCompteResponse", WrapperNamespace="http://ws.hd.saifdine.ma/", IsWrapped=true)]
    public partial class getCompteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.hd.saifdine.ma/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClientWebServiceSoap.ServiceSoap.compte @return;
        
        public getCompteResponse() {
        }
        
        public getCompteResponse(ClientWebServiceSoap.ServiceSoap.compte @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="conversion", WrapperNamespace="http://ws.hd.saifdine.ma/", IsWrapped=true)]
    public partial class conversionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.hd.saifdine.ma/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double arg0;
        
        public conversionRequest() {
        }
        
        public conversionRequest(double arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="conversionResponse", WrapperNamespace="http://ws.hd.saifdine.ma/", IsWrapped=true)]
    public partial class conversionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.hd.saifdine.ma/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double @return;
        
        public conversionResponse() {
        }
        
        public conversionResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapImplChannel : ClientWebServiceSoap.ServiceSoap.WebServiceSoapImpl, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapImplClient : System.ServiceModel.ClientBase<ClientWebServiceSoap.ServiceSoap.WebServiceSoapImpl>, ClientWebServiceSoap.ServiceSoap.WebServiceSoapImpl {
        
        public WebServiceSoapImplClient() {
        }
        
        public WebServiceSoapImplClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapImplClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapImplClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapImplClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientWebServiceSoap.ServiceSoap.getComptesResponse ClientWebServiceSoap.ServiceSoap.WebServiceSoapImpl.getComptes(ClientWebServiceSoap.ServiceSoap.getComptesRequest request) {
            return base.Channel.getComptes(request);
        }
        
        public ClientWebServiceSoap.ServiceSoap.compte[] getComptes() {
            ClientWebServiceSoap.ServiceSoap.getComptesRequest inValue = new ClientWebServiceSoap.ServiceSoap.getComptesRequest();
            ClientWebServiceSoap.ServiceSoap.getComptesResponse retVal = ((ClientWebServiceSoap.ServiceSoap.WebServiceSoapImpl)(this)).getComptes(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientWebServiceSoap.ServiceSoap.getComptesResponse> ClientWebServiceSoap.ServiceSoap.WebServiceSoapImpl.getComptesAsync(ClientWebServiceSoap.ServiceSoap.getComptesRequest request) {
            return base.Channel.getComptesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientWebServiceSoap.ServiceSoap.getComptesResponse> getComptesAsync() {
            ClientWebServiceSoap.ServiceSoap.getComptesRequest inValue = new ClientWebServiceSoap.ServiceSoap.getComptesRequest();
            return ((ClientWebServiceSoap.ServiceSoap.WebServiceSoapImpl)(this)).getComptesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientWebServiceSoap.ServiceSoap.getCompteResponse ClientWebServiceSoap.ServiceSoap.WebServiceSoapImpl.getCompte(ClientWebServiceSoap.ServiceSoap.getCompteRequest request) {
            return base.Channel.getCompte(request);
        }
        
        public ClientWebServiceSoap.ServiceSoap.compte getCompte(int arg0) {
            ClientWebServiceSoap.ServiceSoap.getCompteRequest inValue = new ClientWebServiceSoap.ServiceSoap.getCompteRequest();
            inValue.arg0 = arg0;
            ClientWebServiceSoap.ServiceSoap.getCompteResponse retVal = ((ClientWebServiceSoap.ServiceSoap.WebServiceSoapImpl)(this)).getCompte(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientWebServiceSoap.ServiceSoap.getCompteResponse> ClientWebServiceSoap.ServiceSoap.WebServiceSoapImpl.getCompteAsync(ClientWebServiceSoap.ServiceSoap.getCompteRequest request) {
            return base.Channel.getCompteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientWebServiceSoap.ServiceSoap.getCompteResponse> getCompteAsync(int arg0) {
            ClientWebServiceSoap.ServiceSoap.getCompteRequest inValue = new ClientWebServiceSoap.ServiceSoap.getCompteRequest();
            inValue.arg0 = arg0;
            return ((ClientWebServiceSoap.ServiceSoap.WebServiceSoapImpl)(this)).getCompteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientWebServiceSoap.ServiceSoap.conversionResponse ClientWebServiceSoap.ServiceSoap.WebServiceSoapImpl.conversion(ClientWebServiceSoap.ServiceSoap.conversionRequest request) {
            return base.Channel.conversion(request);
        }
        
        public double conversion(double arg0) {
            ClientWebServiceSoap.ServiceSoap.conversionRequest inValue = new ClientWebServiceSoap.ServiceSoap.conversionRequest();
            inValue.arg0 = arg0;
            ClientWebServiceSoap.ServiceSoap.conversionResponse retVal = ((ClientWebServiceSoap.ServiceSoap.WebServiceSoapImpl)(this)).conversion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientWebServiceSoap.ServiceSoap.conversionResponse> ClientWebServiceSoap.ServiceSoap.WebServiceSoapImpl.conversionAsync(ClientWebServiceSoap.ServiceSoap.conversionRequest request) {
            return base.Channel.conversionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientWebServiceSoap.ServiceSoap.conversionResponse> conversionAsync(double arg0) {
            ClientWebServiceSoap.ServiceSoap.conversionRequest inValue = new ClientWebServiceSoap.ServiceSoap.conversionRequest();
            inValue.arg0 = arg0;
            return ((ClientWebServiceSoap.ServiceSoap.WebServiceSoapImpl)(this)).conversionAsync(inValue);
        }
    }
}
